# -*- coding: utf-8 -*-
"""EAP_Omni_Agent_Platform.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oS5l-NLw0859xUnBopSd2LX-9E8P66Uw?resourcekey=0-au0v6LzdBlE6fGgQTJWjYQ
"""

# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""# EAP: Gemini Omni Flash on Agent Platform

| Author |
| --- |
| [Katie Nguyen](https://github.com/katiemn) |

## Overview

**CONFIDENTIAL, DO NOT CIRCULATE**

<font color='red'> Per the Early Access Program terms, do not publicly share or publish information about this feature (including its outputs) until given permission by the Google Cloud Agent Platform team.</font>

Gemini Omni Flash is a model that understands the world around you so you can animate photos or create videos from any input. Built on Gemini's world understanding and native multimodality, Gemini Omni creates outputs that reflect the logic of the real world and lets you shape them step-by-step through natural conversation.

In this tutorial, you'll learn how to use Gemini Omni Flash in Agent Platform with the Google Gen AI SDK to try out the following scenarios:

- Video generation:
  - Text-to-video generation
  - Providing a reference image as a starting frame
  - Supplying reference inputs (image, audio) to guide video generation
- Video editing:
  - Prompt-based video editing
  - Multi-turn video editing (chat)

**Quota limits:** During the EAP, access is limited to 3 QPM. This cannot be increased until public preview. <font color='red'> Please focus your testing on a very small number of projects, and refrain from sending batch requests across projects.</font>

### Input media

With Gemini Omni, you can use existing media (images, audio, or videos) to generate and edit new videos. The model processes these inputs in one of two ways:

  - **Source Media:** This content acts as the direct foundation for the final output.
    - *Examples:* In image-to-video, the provided image becomes the literal first frame. In video editing, the original video is modified via natural language prompts while keeping its core structure intact.
  - **Reference Media:** This content acts as a guide or inspiration rather than the literal base. You are asking the model to extract a specific style, subject, or mood to creatively reimagine it.
    - *Examples:* Storyboard frames, product images, style guides, audio jingles, or reference scenery. You can also use reference media for video editing—such as providing an image of a new character or art style to apply to a base video.

## Get started

### Install Google Gen AI SDK for Python
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet google-genai

"""### Authenticate your notebook environment (Colab only)

If you are running this notebook on Google Colab, run the following cell to authenticate your environment.
"""

import sys

if "google.colab" in sys.modules:
    from google.colab import auth

    auth.authenticate_user()

"""### Import libraries"""

import os
import base64

import matplotlib.image as img
import matplotlib.pyplot as plt
from IPython.display import Markdown, Video, Audio, Image, display
from google import genai
from google.genai import types

"""### Set Google Cloud project information

To get started using Agent Platform, you must have an existing Google Cloud project and [enable the Agent Platform API](https://console.cloud.google.com/flows/enableapi?apiid=aiplatform.googleapis.com).

Learn more about [setting up a project](https://docs.cloud.google.com/resource-manager/docs/creating-managing-projects) and a [development environment](https://cloud.google.com/docs/authentication/set-up-adc-local-dev-environment).
"""

# fmt: off
PROJECT_ID = "[your-project-id]"  # @param {type: "string", placeholder: "[your-project-id]", isTemplate: true}
# fmt: on
if not PROJECT_ID or PROJECT_ID == "[your-project-id]":
    PROJECT_ID = str(os.environ.get("GOOGLE_CLOUD_PROJECT"))

LOCATION = os.environ.get("GOOGLE_CLOUD_REGION", "global")

client = genai.Client(enterprise=True, project=PROJECT_ID, location=LOCATION,)

"""### Define a helper function to display media"""

def show_video(video_bytes):
    data = base64.b64decode(video_bytes)
    with open("sample.mp4", "wb") as out_file:
        out_file.write(data)
    display(Video("sample.mp4", embed=True, width=600))

"""### Load the video generation model"""

omni_model = "gemini-omni-flash-preview"

"""## Video generation

### Generate videos from a text prompt

With Gemini Omni Flash, you can generate videos directly from text prompts via the [Interactions API](https://docs.cloud.google.com/gemini-enterprise-agent-platform/reference/models/interactions-api). To generate a video in the sample below, specify the following information:
- **Prompt:** A detailed description of the video you would like to see. For best results, consider attributes such as shot framing, motion, style, lighting, location, and action.
  - **Duration:** If you'd like to prompt for video duration, specify a value between 3 - 10 seconds in the prompt.
  - **Aspect ratio:** Specify your desired aspect ratio in the text prompt of either 16:9 or 9:16.

Notes on output videos:
- **Audio generation:** Audio will be generated alongside the output video.
- **Resolution:** 720p
"""

prompt = "A head-on shot of a woman sitting at a desk behind a closed laptop against a pale green wall. She opens the laptop and begins typing on the keyboard. As she types the words 'This is Omni' appear in a curved formation on the wall above her head in a typewriter font. She then gets up from the chair at the desk and touches the writing so that the 'This is Omni' text unfolds into a straight line."

interaction = client.interactions.create(
    model=omni_model,
    input=prompt,
)

contents = []
for step in interaction.steps:
  if step.type == "model_output":
    contents.extend(step.content)

show_video(contents[0].data)

"""### Video generation from a starting image

#### Download the starting image

You can also generate a video by starting with an input image. In this example, you'll locally download an image that's stored in Google Cloud Storage. If you'd like, you can provide the URL of an image to display it below. If you have a local image you'd like to use, you can specify that in the following steps.
"""

!wget -q https://storage.googleapis.com/cloud-samples-data/generative-ai/image/suitcase.png

"""If you'd like to use a different local image, modify the file name in `start`."""

start = "suitcase.png"

fig, ax1 = plt.subplots(1, 1, figsize=(12, 6))
ax1.imshow(img.imread(start))
ax1.axis("off")
plt.show()

prompt = "A single continuous shot of a hard-shell suitcase floating up and spinning in a circle. It stops, stands vertically, unzips alongside and then opens in half. The wheels and shell stay solid. White bubbly retro text reading 'Omnicase' pops out of the center. Colorful cartoon graphics and travel stickers pop up around the text, reading: Los Angeles, New York, Tokyo, Paris."

with open(start, "rb") as f:
    img_b64 = base64.b64encode(f.read()).decode("utf-8")

interaction = client.interactions.create(
    model=omni_model,
    input=[
        {"type": "text", "text": prompt},
        {"type": "image", "mime_type": "image/png", "data": img_b64},
    ]
)

contents = []
for step in interaction.steps:
  if step.type == "model_output":
    contents.extend(step.content)

show_video(contents[0].data)

"""### Reference media inputs in video generation

Reference any kind of media. Combine multiple elements to create your scene–including images, videos, text, and audio-in order to maintain consistency in your generations.

**NOTE:** Video and audio reference inputs are not currently supported.

#### Download and display reference images and audio

In this example, you'll locally download two images that are stored in Google Cloud Storage.
"""

!wget -q https://storage.googleapis.com/cloud-samples-data/generative-ai/image/woman.jpeg

!wget -q https://storage.googleapis.com/cloud-samples-data/generative-ai/image/arcade-game.png

character = "woman.jpeg"
product = "arcade-game.png"

# Display the images
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))
ax1.imshow(img.imread(character))
ax2.imshow(img.imread(product))
ax1.axis("off")
ax2.axis("off")
plt.show()

"""**Tip:** You can supply storyboard reference images to better direct the video without supplying all details in a text prompt."""

prompt = "A woman walks up to the Omni-Sphere game on the side wall of a bowling alley. Bass music begins to play as she starts playing the game by pressing a button. 9:16 aspect ratio. 7 second video."

image_files = [character, product]

images_input = []
for img_path in image_files:
    with open(img_path, "rb") as f:
        img_b64 = base64.b64encode(f.read()).decode("utf-8")
        images_input.append({"type": "image", "mime_type": "image/jpeg",
  "data": img_b64})

interaction = client.interactions.create(
    model=omni_model,
    input=[
        {"type": "text", "text": prompt},
        *images_input,
    ]
)

contents = []
for step in interaction.steps:
  if step.type == "model_output":
    contents.extend(step.content)

show_video(contents[0].data)

"""## Video editing

#### Download and display the video

In this example, you'll locally download a video that's stored in Google Cloud Storage.
"""

from PIL import Image as PIL_IMAGE

video_uri = "gs://cloud-samples-data/generative-ai/video/dog_day1.mp4"
image_uri = "gs://cloud-samples-data/generative-ai/image/chair-cat.png"

!gcloud storage cp {video_uri} {"dog_day1.mp4"}
!gcloud storage cp {image_uri} {"chair-cat.png"}

display(Video("dog_day1.mp4", embed=True, width=600))

fig, ax1 = plt.subplots(1, 1, figsize=(6, 6))
ax1.imshow(PIL_IMAGE.open("chair-cat.png"))
ax1.axis("off")
plt.show()

"""With video editing, you can add, remove, or alter existing objects in the starting video. You can also change the content in the video to a different style."""

prompt = "Change the dog to the cat. Remove the backpack and add a propeller hat. Change the tennis balls to balls of yarn."
interaction = client.interactions.create(
    model=omni_model,
    input=[
        {"type": "text", "text": prompt},
        {"type": "image", "mime_type": "image/png", "uri": image_uri},
        {"type": "video", "mime_type": "video/mp4", "uri": video_uri},
    ]
)

contents = []
for step in interaction.steps:
  if step.type == "model_output":
    contents.extend(step.content)

show_video(contents[0].data)

"""### Multi-turn editing (chat)

You can iteratively chat with the model to continuously change aspects of the video using the example below.

To successfully accomplish this using the Interactions API, make sure to provide the `previous_interaction_id` and the previous chat history in the `input`.
"""

prompt1 = "A claymation explainer of Newton's First Law of Motion, everything is made out of clay, no hands, stop motion, sync character's words to mouth movements, show a cute ball character moving and then being stopped by a wall"

interaction1 = client.interactions.create(
    model=omni_model,
    input=prompt1,
)

contents = []
for step in interaction1.steps:
  if step.type == "model_output":
    contents.extend(step.content)

show_video(contents[0].data)

interaction1.steps

prompt2 = "Now make the same video in a doodle style."

turn2_input = [
    {
      "type": "user_input",
      "content": [
        {
          "type": "text",
          "text": prompt1
        }
      ]
    },
    {
      "type": "model_output",
      "content": [
        {
          "type": "thought",
          "signature":  interaction1.steps[0].signature
        },
        {
          "type": "video",
          "data": contents[0].data,
          "mime_type": "video/mp4"
        }
      ]
    },
    {
      "type": "user_input",
      "content": [
        {
          "type": "text",
          "text": prompt2
        }
      ]
    }
]

interaction2 = client.interactions.create(
    model=omni_model,
    previous_interaction_id=interaction1.id,
    input=turn2_input,
)

contents = []
for step in interaction2.steps:
  if step.type == "model_output":
    contents.extend(step.content)

show_video(contents[0].data)