#!/usr/bin/env bash
#
# deploy-creative-studio.sh
#
# One-file deployment for GenMedia Creative Studio (vertex-ai-creative-studio).
# Implements the documented flow end to end:
#   https://googlecloudplatform.github.io/vertex-ai-creative-studio/core/installation/deploy/
#
#   1. preflight  : tool / auth / project / billing checks
#   2. bootstrap  : enable the APIs Terraform itself needs to call
#   3. source     : clone (or reuse / update) the upstream repository
#   4. terraform  : write terraform.tfvars, init, apply
#   5. dns        : (custom-domain mode) wait for the A record -> LB IP
#   6. build      : submit Cloud Build, which builds the image and rolls Cloud Run
#   7. iap        : (Cloud Run-domain mode) grant the initial user IAP access
#   8. cert       : (custom-domain mode) wait for the managed certificate to go ACTIVE
#
# Safe to re-run: every step is idempotent.
#
# Usage:   ./deploy-creative-studio.sh --project-id my-proj --initial-user me@example.com
#          ./deploy-creative-studio.sh --help
#
set -euo pipefail

readonly SCRIPT_NAME="${0##*/}"
readonly REPO_URL="https://github.com/GoogleCloudPlatform/vertex-ai-creative-studio.git"
readonly SERVICE_NAME="creative-studio"

# ---------------------------------------------------------------------------
# Defaults (every one is overridable by env var or flag)
# ---------------------------------------------------------------------------
# This script lives at the root of the checkout it deploys, so paths anchor to
# the script's own directory — not $PWD, which would break when invoked from
# anywhere else.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

PROJECT_ID="${PROJECT_ID:-}"
REGION="${REGION:-us-central1}"
INITIAL_USER="${INITIAL_USER:-}"
DOMAIN_NAME="${DOMAIN_NAME:-}"
SRC_DIR="${SRC_DIR:-$SCRIPT_DIR}"
GIT_REF="${GIT_REF:-}"
URL_FILE="${URL_FILE:-$SCRIPT_DIR/creative-studio-url.txt}"

ASSUME_YES=0
SKIP_CLONE=0
SKIP_TERRAFORM=0
SKIP_BUILD=0
SKIP_DNS_WAIT=0
SKIP_CERT_WAIT=0
DRY_RUN=0
DESTROY=0
ADD_USER=""
DNS_TIMEOUT="${DNS_TIMEOUT:-1800}"   # 30 min for the A record to propagate
CERT_TIMEOUT="${CERT_TIMEOUT:-3600}" # up to 60 min for a Google-managed cert
EXTRA_TFVARS=()

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------
if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]]; then
  C_RESET=$'\033[0m'; C_RED=$'\033[31m'; C_GREEN=$'\033[32m'
  C_YELLOW=$'\033[33m'; C_BLUE=$'\033[34m'; C_BOLD=$'\033[1m'
else
  C_RESET=""; C_RED=""; C_GREEN=""; C_YELLOW=""; C_BLUE=""; C_BOLD=""
fi

log()   { printf '%s[%s]%s %s\n' "$C_BLUE"   "$(date +%H:%M:%S)" "$C_RESET" "$*"; }
ok()    { printf '%s  ✓%s %s\n'  "$C_GREEN"  "$C_RESET" "$*"; }
warn()  { printf '%s  !%s %s\n'  "$C_YELLOW" "$C_RESET" "$*" >&2; }
err()   { printf '%s  ✗%s %s\n'  "$C_RED"    "$C_RESET" "$*" >&2; }
die()   { err "$*"; exit 1; }
step()  { printf '\n%s==> %s%s\n' "$C_BOLD" "$*" "$C_RESET"; }

# Echo a command, then run it (or just echo it under --dry-run).
run() {
  printf '%s    $ %s%s\n' "$C_BLUE" "$*" "$C_RESET"
  (( DRY_RUN )) && return 0
  "$@"
}

# Same, but from a directory. Under --dry-run the directory may not exist yet
# (nothing was cloned), so never attempt the cd.
run_in() {
  local dir="$1"; shift
  printf '%s    $ (cd %s && %s)%s\n' "$C_BLUE" "$dir" "$*" "$C_RESET"
  (( DRY_RUN )) && return 0
  ( cd "$dir" && "$@" )
}

confirm() {
  local prompt="$1" reply
  (( ASSUME_YES )) && return 0
  if [[ ! -t 0 ]] && [[ ! -r /dev/tty ]]; then
    die "'$prompt' needs confirmation but there is no terminal. Re-run with --yes."
  fi
  read -r -p "$prompt [y/N] " reply < /dev/tty || true
  [[ "$reply" =~ ^[Yy]$ ]]
}

usage() {
  cat <<EOF
${C_BOLD}$SCRIPT_NAME${C_RESET} — one-shot deployment of GenMedia Creative Studio to Google Cloud.

${C_BOLD}USAGE${C_RESET}
  $SCRIPT_NAME --project-id PROJECT --initial-user EMAIL [--domain DOMAIN] [options]

${C_BOLD}DEPLOYMENT MODES${C_RESET}
  Custom domain (default when --domain is given)
      HTTPS load balancer + Google-managed certificate + IAP. Requires you to
      create a DNS A record pointing at the load balancer IP the script prints.
  Cloud Run domain (when --domain is omitted)
      Uses the autogenerated *.run.app URL with IAP-for-Cloud-Run (preview).
      No DNS needed.

${C_BOLD}REQUIRED${C_RESET}
  --project-id ID       Google Cloud project ID          (env PROJECT_ID)
  --initial-user EMAIL  First user granted app access    (env INITIAL_USER)

${C_BOLD}OPTIONS${C_RESET}
  --region REGION       Deployment region (default: us-central1, env REGION)
  --domain DOMAIN       Custom domain, enables the load balancer (env DOMAIN_NAME)
  --src-dir DIR         Where to clone/find the repo (default: this script's directory)
  --url-file PATH       Write the deployed URL here (default: <script dir>/creative-studio-url.txt)
  --git-ref REF         Branch/tag/commit to check out after cloning
  --tfvar 'k = v'       Extra line appended to terraform.tfvars (repeatable, raw HCL).
                        e.g. --tfvar 'model_id = "gemini-3.5-flash"'
  -y, --yes             Non-interactive; assume yes and auto-approve Terraform
  --dry-run             Print every command without executing it

${C_BOLD}STEP CONTROL${C_RESET}
  --skip-clone          Use --src-dir as-is, do not clone or pull
  --skip-terraform      Do not run Terraform (build/deploy only)
  --skip-build          Do not submit the Cloud Build (infrastructure only)
  --skip-dns-wait       Do not block waiting for DNS propagation
  --skip-cert-wait      Do not block waiting for the managed certificate
  --dns-timeout SECS    DNS wait budget (default: $DNS_TIMEOUT)
  --cert-timeout SECS   Certificate wait budget (default: $CERT_TIMEOUT)

${C_BOLD}MAINTENANCE MODES${C_RESET}
  --add-user EMAIL      Grant an existing deployment's IAP + asset-bucket access
                        to another user, then exit
  --destroy             Tear the deployment down with 'terraform destroy'

${C_BOLD}EXAMPLES${C_RESET}
  # Cloud Run URL, fully unattended
  $SCRIPT_NAME --project-id my-proj --initial-user me@example.com --yes

  # Custom domain
  $SCRIPT_NAME --project-id my-proj --initial-user me@example.com \\
      --domain creativestudio.example.com

  # Ship a code change to an existing deployment
  $SCRIPT_NAME --project-id my-proj --skip-terraform --yes

  # Add a colleague
  $SCRIPT_NAME --project-id my-proj --add-user colleague@example.com
EOF
}

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
parse_args() {
  while (( $# )); do
    case "$1" in
      --project-id)     PROJECT_ID="${2:?--project-id needs a value}"; shift 2 ;;
      --region)         REGION="${2:?--region needs a value}"; shift 2 ;;
      --initial-user)   INITIAL_USER="${2:?--initial-user needs a value}"; shift 2 ;;
      --domain)         DOMAIN_NAME="${2:?--domain needs a value}"; shift 2 ;;
      --src-dir)        SRC_DIR="${2:?--src-dir needs a value}"; shift 2 ;;
      --url-file)       URL_FILE="${2:?--url-file needs a value}"; shift 2 ;;
      --git-ref)        GIT_REF="${2:?--git-ref needs a value}"; shift 2 ;;
      --tfvar)          EXTRA_TFVARS+=("${2:?--tfvar needs a value}"); shift 2 ;;
      --add-user)       ADD_USER="${2:?--add-user needs a value}"; shift 2 ;;
      --dns-timeout)    DNS_TIMEOUT="${2:?--dns-timeout needs a value}"; shift 2 ;;
      --cert-timeout)   CERT_TIMEOUT="${2:?--cert-timeout needs a value}"; shift 2 ;;
      -y|--yes)         ASSUME_YES=1; shift ;;
      --dry-run)        DRY_RUN=1; shift ;;
      --destroy)        DESTROY=1; shift ;;
      --skip-clone)     SKIP_CLONE=1; shift ;;
      --skip-terraform) SKIP_TERRAFORM=1; shift ;;
      --skip-build)     SKIP_BUILD=1; shift ;;
      --skip-dns-wait)  SKIP_DNS_WAIT=1; shift ;;
      --skip-cert-wait) SKIP_CERT_WAIT=1; shift ;;
      -h|--help)        usage; exit 0 ;;
      *)                usage >&2; die "Unknown argument: $1" ;;
    esac
  done
}

# USE_LB is derived, not configured: a domain means a load balancer.
derive_config() {
  if [[ -n "$DOMAIN_NAME" ]]; then USE_LB=true; else USE_LB=false; fi
  ASSETS_BUCKET_FALLBACK="creative-studio-${PROJECT_ID}-assets"
}

# ---------------------------------------------------------------------------
# Step 1 — preflight
# ---------------------------------------------------------------------------
require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1 — $2"
}

preflight() {
  step "Preflight checks"

  (( BASH_VERSINFO[0] >= 4 )) || warn "bash ${BASH_VERSION} is old; bash 4+ recommended."

  require_cmd gcloud    "install the Google Cloud SDK: https://cloud.google.com/sdk/docs/install"
  require_cmd git       "install git"
  ok "$(gcloud version 2>/dev/null | head -1)"

  if (( ! SKIP_TERRAFORM )) || (( DESTROY )); then
    require_cmd terraform "install Terraform: https://developer.hashicorp.com/terraform/downloads"
    local tf_ver
    tf_ver="$(terraform version -json 2>/dev/null \
      | sed -n 's/.*"terraform_version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)"
    ok "terraform ${tf_ver:-unknown}"
  fi

  [[ -n "$PROJECT_ID" ]] || die "--project-id (or PROJECT_ID) is required."
  if [[ -z "$INITIAL_USER" && -z "$ADD_USER" && $DESTROY -eq 0 ]]; then
    die "--initial-user (or INITIAL_USER) is required."
  fi
  if [[ -n "$INITIAL_USER" && "$INITIAL_USER" != *@* ]]; then
    die "--initial-user must be an email address, got: $INITIAL_USER"
  fi
  if [[ -n "$DOMAIN_NAME" && "$DOMAIN_NAME" != *.* ]]; then
    die "--domain must be a fully-qualified domain name, got: $DOMAIN_NAME"
  fi

  # Authenticated gcloud user.
  local account
  account="$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -1)"
  [[ -n "$account" ]] || die "No active gcloud account. Run: gcloud auth login"
  ok "gcloud account: $account"

  # Terraform authenticates via Application Default Credentials, not the gcloud
  # user. ADC login opens a browser, so only offer it when there is a terminal.
  if gcloud auth application-default print-access-token >/dev/null 2>&1; then
    ok "Application Default Credentials present"
  else
    warn "No Application Default Credentials found — Terraform needs them."
    if [[ ! -t 0 ]] && [[ ! -r /dev/tty ]]; then
      die "Run this first (it needs a browser): gcloud auth application-default login"
    fi
    confirm "Run 'gcloud auth application-default login' now?" \
      || die "Aborting. Run: gcloud auth application-default login"
    run gcloud auth application-default login
    if (( DRY_RUN )); then
      warn "(dry run) ADC still absent; the real run will need them."
    elif gcloud auth application-default print-access-token >/dev/null 2>&1; then
      ok "Application Default Credentials present"
    else
      die "Application Default Credentials are still missing after login."
    fi
  fi

  # Project reachable?
  local project_number
  if ! project_number="$(gcloud projects describe "$PROJECT_ID" --format='value(projectNumber)' 2>/dev/null)"; then
    die "Cannot read project '$PROJECT_ID'. Check the ID and your permissions."
  fi
  ok "Project $PROJECT_ID (number $project_number)"

  # Billing must be on; a missing permission here is a warning, not a failure.
  local billing
  if billing="$(gcloud billing projects describe "$PROJECT_ID" \
        --format='value(billingEnabled)' 2>/dev/null)"; then
    if [[ "$billing" == "True" ]]; then
      ok "Billing enabled"
    else
      die "Billing is not enabled on $PROJECT_ID. Vertex AI, Cloud Run and Cloud Build all require it."
    fi
  else
    warn "Could not verify billing (missing billing.projects.get). Continuing."
  fi
}

# ---------------------------------------------------------------------------
# Step 2 — bootstrap APIs
#
# Terraform's project_services module calls Service Usage and Cloud Resource
# Manager to turn on everything else, so those two must already be on. IAM is
# added because the very first resources are service accounts.
# ---------------------------------------------------------------------------
bootstrap_apis() {
  step "Enabling bootstrap APIs"
  local apis=(serviceusage.googleapis.com cloudresourcemanager.googleapis.com iam.googleapis.com)
  local enabled missing=()

  enabled="$(gcloud services list --enabled --project="$PROJECT_ID" \
              --format='value(config.name)' 2>/dev/null || true)"
  local api
  for api in "${apis[@]}"; do
    if grep -qx "$api" <<<"$enabled"; then
      ok "$api already enabled"
    else
      missing+=("$api")
    fi
  done

  if (( ${#missing[@]} )); then
    run gcloud services enable "${missing[@]}" --project="$PROJECT_ID"
    ok "Enabled: ${missing[*]}"
    log "Waiting 20s for API enablement to propagate…"
    (( DRY_RUN )) || sleep 20
  fi
}

# ---------------------------------------------------------------------------
# Step 3 — source code
# ---------------------------------------------------------------------------
fetch_source() {
  step "Preparing source at $SRC_DIR"

  if (( SKIP_CLONE )); then
    [[ -f "$SRC_DIR/main.tf" ]] || die "--skip-clone given but $SRC_DIR/main.tf not found."
    ok "Using existing checkout (clone/pull skipped)"
    return
  fi

  if [[ -d "$SRC_DIR/.git" ]]; then
    log "Repository exists; updating."
    if [[ -n "$(git -C "$SRC_DIR" status --porcelain 2>/dev/null | grep -v 'terraform.tfvars')" ]]; then
      warn "Local modifications in $SRC_DIR — skipping 'git pull' to avoid clobbering them."
    else
      run git -C "$SRC_DIR" pull --ff-only || warn "git pull failed; continuing with the current checkout."
    fi
  elif [[ -e "$SRC_DIR" ]]; then
    die "$SRC_DIR exists but is not a git checkout. Move it aside or pass --src-dir."
  else
    run git clone "$REPO_URL" "$SRC_DIR"
  fi

  if [[ -n "$GIT_REF" ]]; then
    run git -C "$SRC_DIR" checkout "$GIT_REF"
    ok "Checked out $GIT_REF"
  fi

  (( DRY_RUN )) || [[ -f "$SRC_DIR/main.tf" ]] \
    || die "$SRC_DIR/main.tf missing — the repository layout changed unexpectedly."
  ok "Source ready"
}

# ---------------------------------------------------------------------------
# Step 4 — Terraform
# ---------------------------------------------------------------------------
write_tfvars() {
  local tfvars="$SRC_DIR/terraform.tfvars"

  if [[ -f "$tfvars" ]]; then
    local backup="${tfvars}.bak.$(date +%Y%m%d%H%M%S)"
    log "Backing up existing terraform.tfvars -> ${backup##*/}"
    (( DRY_RUN )) || cp "$tfvars" "$backup"
  fi

  log "Writing terraform.tfvars"
  if (( DRY_RUN )); then
    printf '%s    (dry-run) would write %s%s\n' "$C_BLUE" "$tfvars" "$C_RESET"
    return
  fi

  {
    echo "# Generated by $SCRIPT_NAME on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "project_id   = \"$PROJECT_ID\""
    echo "region       = \"$REGION\""
    echo "initial_user = \"$INITIAL_USER\""
    if [[ "$USE_LB" == "true" ]]; then
      echo "domain       = \"$DOMAIN_NAME\""
    else
      echo "use_lb       = false"
    fi
    local extra
    for extra in "${EXTRA_TFVARS[@]:-}"; do
      [[ -n "$extra" ]] && echo "$extra"
    done
  } > "$tfvars"

  terraform fmt "$tfvars" >/dev/null 2>&1 || true   # cosmetic alignment only
  printf '%s' "$C_BLUE"; sed 's/^/      /' "$tfvars"; printf '%s' "$C_RESET"
}

terraform_apply() {
  step "Terraform — provisioning infrastructure"
  write_tfvars

  run_in "$SRC_DIR" terraform init -upgrade -input=false \
    || die "'terraform init' failed. See the errors above."

  local apply_args=(apply -input=false)
  (( ASSUME_YES )) && apply_args+=(-auto-approve)

  run_in "$SRC_DIR" terraform "${apply_args[@]}" \
    || die "'terraform apply' failed. Fix the errors above and re-run (the script is idempotent)."

  ok "Infrastructure applied"
}

terraform_destroy() {
  step "Destroying infrastructure"
  [[ -f "$SRC_DIR/main.tf" ]] || die "No Terraform config at $SRC_DIR."
  warn "This deletes the Cloud Run service, load balancer, Firestore data and buckets."
  confirm "Really destroy the deployment in $PROJECT_ID?" || die "Aborted."

  local args=(destroy -input=false -var=enable_data_deletion=true)
  (( ASSUME_YES )) && args+=(-auto-approve)
  # Buckets refuse to delete while non-empty unless force_destroy was set.
  run_in "$SRC_DIR" terraform "${args[@]}"
  ok "Destroyed"
}

tf_output() {
  local name="$1"
  (( DRY_RUN )) && { echo ""; return; }
  ( cd "$SRC_DIR" && terraform output -raw "$name" 2>/dev/null ) || echo ""
}

# ---------------------------------------------------------------------------
# Step 5 — DNS (custom-domain mode only)
#
# The managed certificate can only be issued once the A record resolves to the
# load balancer. Certificate issuance fails with FAILED_NOT_VISIBLE if the
# record is wrong or arrives too late, so block here rather than after.
# ---------------------------------------------------------------------------
resolve_a_record() {
  local host="$1"
  if command -v dig >/dev/null 2>&1; then
    dig +short A "$host" @8.8.8.8 2>/dev/null | grep -E '^[0-9]+(\.[0-9]+){3}$' || true
  elif command -v host >/dev/null 2>&1; then
    host -t A "$host" 2>/dev/null | awk '/has address/ {print $NF}' || true
  elif command -v nslookup >/dev/null 2>&1; then
    nslookup -type=A "$host" 2>/dev/null | awk '/^Address: /{print $2}' || true
  else
    warn "No dig/host/nslookup available; cannot verify DNS."
    return 1
  fi
}

wait_for_dns() {
  local lb_ip="$1"

  printf '\n%s  ACTION REQUIRED%s  Create this DNS record:\n\n' "$C_BOLD$C_YELLOW" "$C_RESET"
  printf '      %-40s A     %s\n\n' "$DOMAIN_NAME" "$lb_ip"
  printf '  Google Cloud DNS: https://cloud.google.com/dns/docs/records\n'

  if (( SKIP_DNS_WAIT )); then
    warn "Skipping DNS wait (--skip-dns-wait)."
    return 0
  fi

  log "Waiting up to $((DNS_TIMEOUT / 60))m for $DOMAIN_NAME to resolve to $lb_ip (Ctrl-C to stop waiting)…"
  local deadline=$(( SECONDS + DNS_TIMEOUT )) ips
  while (( SECONDS < deadline )); do
    ips="$(resolve_a_record "$DOMAIN_NAME")" || return 0
    if grep -qx "$lb_ip" <<<"${ips:-}"; then
      ok "$DOMAIN_NAME -> $lb_ip"
      return 0
    fi
    if [[ -n "${ips:-}" ]]; then
      warn "$DOMAIN_NAME currently resolves to: $(tr '\n' ' ' <<<"$ips")— expected $lb_ip"
    fi
    sleep 30
  done

  warn "DNS did not converge within the timeout."
  warn "The certificate will stay PROVISIONING (or fail as FAILED_NOT_VISIBLE) until it does."
  confirm "Continue with the build anyway?" || die "Aborted; fix DNS and re-run."
}

# ---------------------------------------------------------------------------
# Step 6 — Cloud Build (builds the image and updates Cloud Run)
# ---------------------------------------------------------------------------
submit_build() {
  step "Building and deploying the container image"

  local build_sa="builds-${SERVICE_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
  local staging="gs://run-resources-${PROJECT_ID}-${REGION}/services/${SERVICE_NAME}"

  log "Cloud Build service account: $build_sa"
  log "Source staging: $staging"
  log "This takes roughly 5-10 minutes."

  # Prefer the repo's own build.sh so we track upstream if it changes; it is a
  # bare command file with no shebang, so invoke it through bash explicitly.
  if [[ -f "$SRC_DIR/build.sh" ]] || (( DRY_RUN )); then
    run_in "$SRC_DIR" env "PROJECT_ID=$PROJECT_ID" "REGION=$REGION" bash ./build.sh \
      || die "Cloud Build failed. See the build log URL above."
  else
    run_in "$SRC_DIR" gcloud builds submit . \
      --project="$PROJECT_ID" \
      --region="$REGION" \
      --gcs-source-staging-dir="$staging" \
      --service-account="projects/${PROJECT_ID}/serviceAccounts/${build_sa}" \
      || die "Cloud Build failed. See the build log URL above."
  fi

  ok "Image built and Cloud Run service updated"
}

# ---------------------------------------------------------------------------
# Step 7 — IAP access for the Cloud Run-domain mode
#
# In load-balancer mode Terraform already grants the initial user via
# google_iap_web_iam_member; IAP-for-Cloud-Run has no Terraform resource yet,
# so it is granted here.
# ---------------------------------------------------------------------------
grant_cloudrun_iap() {
  step "Granting IAP access to $INITIAL_USER"

  if ! gcloud beta --help >/dev/null 2>&1; then
    warn "gcloud 'beta' component missing; installing."
    run gcloud components install beta --quiet || \
      die "Could not install the gcloud beta component; install it and re-run with --skip-terraform --skip-build."
  fi

  run gcloud beta iap web add-iam-policy-binding \
    --project="$PROJECT_ID" \
    --region="$REGION" \
    --member="user:$INITIAL_USER" \
    --role=roles/iap.httpsResourceAccessor \
    --resource-type=cloud-run \
    --service="$SERVICE_NAME" \
    || die "Failed to grant IAP access. Grant 'IAP-Secured Web App User' manually in the console."

  ok "$INITIAL_USER can sign in"
}

# ---------------------------------------------------------------------------
# Step 8 — managed certificate (custom-domain mode only)
# ---------------------------------------------------------------------------
wait_for_certificate() {
  if (( SKIP_CERT_WAIT )); then
    warn "Skipping certificate wait (--skip-cert-wait)."
    return 0
  fi

  step "Waiting for the Google-managed certificate"
  log "Provisioning can take up to 60 minutes after DNS propagates (Ctrl-C to stop waiting)."

  local deadline=$(( SECONDS + CERT_TIMEOUT )) line name status
  while (( SECONDS < deadline )); do
    line="$(gcloud compute ssl-certificates list \
              --project="$PROJECT_ID" \
              --filter="managed.domains:($DOMAIN_NAME)" \
              --format='value(name,managed.status)' 2>/dev/null | head -1 || true)"
    if [[ -z "$line" ]]; then
      warn "No managed certificate found for $DOMAIN_NAME yet…"
    else
      name="${line%%$'\t'*}"; status="${line##*$'\t'}"
      case "$status" in
        ACTIVE)
          ok "Certificate '$name' is ACTIVE"
          return 0 ;;
        FAILED_NOT_VISIBLE)
          err "Certificate '$name' is FAILED_NOT_VISIBLE — the A record is wrong or arrived too late."
          err "Fix DNS, then delete and re-apply the certificate:"
          err "  https://cloud.google.com/load-balancing/docs/ssl-certificates/troubleshooting"
          return 1 ;;
        *)
          log "Certificate '$name': $status" ;;
      esac
    fi
    sleep 60
  done

  warn "Certificate not ACTIVE within $((CERT_TIMEOUT / 60))m. Track it here:"
  warn "  https://console.cloud.google.com/security/ccm/list/lbCertificates?project=$PROJECT_ID"
  return 0
}

# ---------------------------------------------------------------------------
# Maintenance mode — add a user to an existing deployment
#
# Two grants are needed: IAP to reach the app, and Storage Object Viewer so the
# signed GCS URLs the app hands out actually resolve for that user.
# ---------------------------------------------------------------------------
add_user() {
  step "Granting access to $ADD_USER"
  [[ "$ADD_USER" == *@* ]] || die "--add-user must be an email address."

  local bucket
  bucket="$(tf_output assets-bucket)"
  [[ -n "$bucket" ]] && ok "Assets bucket from Terraform state: $bucket" || {
    bucket="$ASSETS_BUCKET_FALLBACK"
    warn "No Terraform state readable; assuming bucket $bucket"
  }

  # Which IAP surface depends on how it was deployed; detect instead of asking.
  local lb_ip
  lb_ip="$(tf_output load-balancer-ip)"
  if [[ -n "$lb_ip" ]]; then
    log "Load-balancer deployment detected — granting project-level IAP access."
    run gcloud iap web add-iam-policy-binding \
      --project="$PROJECT_ID" \
      --member="user:$ADD_USER" \
      --role=roles/iap.httpsResourceAccessor \
      --resource-type=iap_web
  else
    log "Cloud Run deployment — granting IAP access on the service."
    run gcloud beta iap web add-iam-policy-binding \
      --project="$PROJECT_ID" \
      --region="$REGION" \
      --member="user:$ADD_USER" \
      --role=roles/iap.httpsResourceAccessor \
      --resource-type=cloud-run \
      --service="$SERVICE_NAME"
  fi

  run gcloud storage buckets add-iam-policy-binding "gs://${bucket}" \
    --project="$PROJECT_ID" \
    --member="user:$ADD_USER" \
    --role=roles/storage.objectViewer

  ok "$ADD_USER granted app access and asset-read access"
}

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
# The authoritative Cloud Run URL, straight from the service. Terraform's
# cloud-run-app-url output *constructs* a project-number URL; the service may
# actually be served under a different hostname, so ask the API and only fall
# back to the Terraform output.
resolve_app_url() {
  local url=""
  if [[ "$USE_LB" == "true" ]]; then
    echo "https://${DOMAIN_NAME}"
    return
  fi
  (( DRY_RUN )) || url="$(gcloud run services describe "$SERVICE_NAME" \
      --region="$REGION" --project="$PROJECT_ID" \
      --format='value(status.url)' 2>/dev/null || true)"
  echo "${url:-$(tf_output cloud-run-app-url)}"
}

# Record the deployment URL (and how to reach it) next to the script.
write_url_file() {
  local app_url="$1" assets_bucket="$2" lb_ip="$3"

  if (( DRY_RUN )); then
    warn "(dry run) would write $URL_FILE"
    return
  fi

  {
    echo "$app_url"
    echo
    echo "# GenMedia Creative Studio — deployed $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# project       : $PROJECT_ID"
    echo "# region        : $REGION"
    echo "# service       : $SERVICE_NAME"
    echo "# mode          : $([[ "$USE_LB" == "true" ]] && echo "custom domain + HTTPS load balancer" || echo "Cloud Run domain + IAP")"
    [[ -n "$lb_ip" ]] && echo "# load balancer : $lb_ip"
    echo "# assets bucket : ${assets_bucket:-$ASSETS_BUCKET_FALLBACK}"
    echo "# initial user  : $INITIAL_USER"
    echo "#"
    echo "# Access is behind IAP. Sign in as a user granted roles/iap.httpsResourceAccessor."
    echo "# Newly granted users take a few minutes to propagate; use a private window to"
    echo "# avoid a cached IAP denial cookie."
  } > "$URL_FILE" || { warn "Could not write $URL_FILE"; return; }

  ok "URL saved to $URL_FILE"
}

summary() {
  local app_url assets_bucket lb_ip=""
  assets_bucket="$(tf_output assets-bucket)"
  [[ "$USE_LB" == "true" ]] && lb_ip="$(tf_output load-balancer-ip)"
  app_url="$(resolve_app_url)"

  printf '\n%s%s\n' "$C_BOLD" "────────────────────────────────────────────────────────────"
  printf '  GenMedia Creative Studio deployed%s\n\n' "$C_RESET"
  printf '  Project        : %s\n' "$PROJECT_ID"
  printf '  Region         : %s\n' "$REGION"
  printf '  Mode           : %s\n' "$([[ "$USE_LB" == "true" ]] && echo "custom domain + HTTPS load balancer" || echo "Cloud Run domain + IAP")"
  [[ -n "$lb_ip" ]]         && printf '  Load balancer  : %s\n' "$lb_ip"
  printf '  Assets bucket  : %s\n' "${assets_bucket:-$ASSETS_BUCKET_FALLBACK}"
  printf '  Initial user   : %s\n' "$INITIAL_USER"
  printf '\n  %sURL%s            : %s\n' "$C_GREEN" "$C_RESET" "${app_url:-<see terraform output>}"
  printf '\n  Next:\n'
  printf '    Add a user   : %s --project-id %s --add-user someone@example.com\n' "$SCRIPT_NAME" "$PROJECT_ID"
  printf '    Ship a change: %s --project-id %s --skip-terraform --yes\n' "$SCRIPT_NAME" "$PROJECT_ID"
  printf '    Tear down    : %s --project-id %s --destroy\n' "$SCRIPT_NAME" "$PROJECT_ID"
  printf '%s%s%s\n' "$C_BOLD" "────────────────────────────────────────────────────────────" "$C_RESET"

  write_url_file "$app_url" "$assets_bucket" "$lb_ip"
}

# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
main() {
  parse_args "$@"
  derive_config

  printf '%s%s%s\n' "$C_BOLD" "GenMedia Creative Studio — deployment" "$C_RESET"
  (( DRY_RUN )) && warn "DRY RUN — no changes will be made."

  preflight

  if [[ -n "$ADD_USER" ]]; then
    add_user
    exit 0
  fi

  if (( DESTROY )); then
    terraform_destroy
    exit 0
  fi

  printf '\n  Project      : %s\n' "$PROJECT_ID"
  printf '  Region       : %s\n' "$REGION"
  printf '  Initial user : %s\n' "$INITIAL_USER"
  printf '  Mode         : %s\n' "$([[ "$USE_LB" == "true" ]] && echo "custom domain ($DOMAIN_NAME)" || echo "Cloud Run domain")"
  printf '  Source dir   : %s\n\n' "$SRC_DIR"
  confirm "Proceed?" || die "Aborted."

  bootstrap_apis
  fetch_source

  if (( SKIP_TERRAFORM )); then
    warn "Skipping Terraform (--skip-terraform)."
  else
    terraform_apply
  fi

  if [[ "$USE_LB" == "true" ]]; then
    local lb_ip
    lb_ip="$(tf_output load-balancer-ip)"
    if [[ -n "$lb_ip" ]]; then
      wait_for_dns "$lb_ip"
    else
      warn "No load-balancer IP in Terraform state; skipping the DNS check."
    fi
  fi

  if (( SKIP_BUILD )); then
    warn "Skipping Cloud Build (--skip-build). The Cloud Run service still runs the placeholder image."
  else
    submit_build
  fi

  if [[ "$USE_LB" == "true" ]]; then
    wait_for_certificate || true
  elif (( ! SKIP_TERRAFORM )) || (( ! SKIP_BUILD )); then
    grant_cloudrun_iap
  fi

  summary
}

main "$@"
