# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Test script to validate C2PA metadata in images generated by Gemini 3 Pro Image.
"""

import json
import os
import time
from datetime import datetime

import c2pa
from google import genai
from google.genai import types

# Configuration
PROJECT_ID = os.getenv("PROJECT_ID")
LOCATION = os.getenv("LOCATION", "us-central1")
MODEL_ID = "gemini-3-pro-image-preview" # Nano Banana Pro
OUTPUT_DIR = "test/c2pa/output"

def generate_image(prompt: str, output_path: str):
    """Generates an image using Gemini and saves it locally."""
    print(f"Generating image with model {MODEL_ID}...")
    client = genai.Client(vertexai=True, project=PROJECT_ID, location=LOCATION)
    
    start_time = time.time()
    
    try:
        response = client.models.generate_content(
            model=MODEL_ID,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
                image_config=types.ImageConfig(
                    aspect_ratio="1:1",
                    output_mime_type="image/png"
                )
            )
        )
        end_time = time.time()
        print(f"Generation took {end_time - start_time:.2f} seconds.")

        if response.candidates and response.candidates[0].content.parts:
            for part in response.candidates[0].content.parts:
                if part.inline_data and part.inline_data.mime_type == "image/png":
                    with open(output_path, "wb") as f:
                        f.write(part.inline_data.data)
                    print(f"Image saved to {output_path}")
                    return True
            print("No image part found in response.")
            return False
        else:
            print("No candidates returned.")
            return False

    except Exception as e:
        print(f"Error during generation: {e}")
        return False

def inspect_c2pa_metadata(image_path: str):
    """Reads and prints C2PA metadata from the image."""
    print(f"\nInspecting C2PA metadata for {image_path}...")
    
    try:
        with c2pa.Reader(image_path) as reader:
            manifest_json = reader.json()
            manifest_store = json.loads(manifest_json)
            
            print("\n--- C2PA Manifest Store ---")
            # print(json.dumps(manifest_store, indent=2))
            
            active_manifest_label = manifest_store.get("active_manifest")
            print(f"\nActive Manifest: {active_manifest_label}")
            
            if active_manifest_label:
                manifest = manifest_store["manifests"][active_manifest_label]
                
                print(f"Claim Generator: {manifest.get('claim_generator', 'Unknown')}")
                print(f"Title: {manifest.get('title', 'Unknown')}")
                
                print("\nAssertions:")
                for assertion in manifest.get("assertions", []):
                    print(f"- Label: {assertion.get('label')}")
                    # Check for creation action
                    if assertion.get("label") == "c2pa.actions":
                        actions = assertion.get("data", {}).get("actions", [])
                        for action in actions:
                            print(f"  - Action: {action.get('action')}")
                            print(f"  - Source Type: {action.get('digitalSourceType')}")

            else:
                print("No active manifest found.")

            return manifest_store

    except Exception as e:
        print(f"Error reading C2PA metadata: {e}")
        return None

def main():
    if not PROJECT_ID:
        print("Error: PROJECT_ID environment variable not set.")
        return

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    image_filename = f"gemini_c2pa_test_{timestamp}.png"
    image_path = os.path.join(OUTPUT_DIR, image_filename)
    
    prompt = "a futuristic robot painting a canvas, digital art style"
    
    if generate_image(prompt, image_path):
        metadata = inspect_c2pa_metadata(image_path)
        
        if metadata and metadata.get("active_manifest"):
            print("\n✅ SUCCESS: Valid C2PA manifest found.")
        else:
            print("\n❌ FAILURE: No valid C2PA manifest found.")

if __name__ == "__main__":
    main()
