# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Consolidated configuration for Gemini TTS models, voices, and languages."""

GEMINI_TTS_MODELS = {
    "gemini-2.5-flash-tts": {
        "id": "gemini-2.5-flash-tts",
        "label": "Gemini 2.5 Flash TTS",
        "description": "Fast, high-quality text-to-speech model.",
        "tags": ["TTS", "Gemini 2.5 Flash"],
        "version": "2.5-flash",
    },
    "gemini-2.5-pro-tts": {
        "id": "gemini-2.5-pro-tts",
        "label": "Gemini 2.5 Pro TTS",
        "description": "Highest-quality text-to-speech model.",
        "tags": ["TTS", "Gemini 2.5 Pro"],
        "version": "2.5-pro",
    },
    "gemini-2.5-flash-lite-preview-tts": {
        "id": "gemini-2.5-flash-lite-preview-tts",
        "label": "Gemini 2.5 Flash Lite TTS",
        "description": "Lightweight, low-latency text-to-speech model.",
        "tags": ["TTS", "Gemini 2.5 Flash Lite"],
        "version": "2.5-flash-lite",
    },
}

GEMINI_TTS_MODEL_NAMES = list(GEMINI_TTS_MODELS.keys())

GEMINI_TTS_VOICES = [
    "Achernar", "Achird", "Algenib", "Algieba", "Alnilam", "Aoede", "Autonoe",
    "Callirrhoe", "Charon", "Despina", "Enceladus", "Erinome", "Fenrir",
    "Gacrux", "Iapetus", "Kore", "Laomedeia", "Leda", "Orus", "Pulcherrima",
    "Puck", "Rasalgethi", "Sadachbia", "Sadaltager", "Schedar", "Sulafat",
    "Umbriel", "Vindemiatrix", "Zephyr", "Zubenelgenubi",
]

GEMINI_TTS_ENCODINGS = {
    "X-SAMPA": "PHONETIC_ENCODING_X_SAMPA",
    "IPA": "PHONETIC_ENCODING_IPA",
    "Pinyin": "PHONETIC_ENCODING_PINYIN",
    "Japanese": "PHONETIC_ENCODING_JAPANESE_YOMIGANA",
}

CHIRP3_HD_LANGUAGES = {
    "Arabic (Generic)": "ar-XA",
    "Bengali (India)": "bn-IN",
    "Danish (Denmark)": "da-DK",
    "Dutch (Belgium)": "nl-BE",
    "Dutch (Netherlands)": "nl-NL",
    "English (Australia)": "en-AU",
    "English (India)": "en-IN",
    "English (United Kingdom)": "en-GB",
    "English (United States)": "en-US",
    "Finnish (Finland)": "fi-FI",
    "French (Canada)": "fr-CA",
    "French (France)": "fr-FR",
    "German (Germany)": "de-DE",
    "Gujarati (India)": "gu-IN",
    "Hindi (India)": "hi-IN",
    "Indonesian (Indonesia)": "id-ID",
    "Italian (Italy)": "it-IT",
    "Japanese (Japan)": "ja-JP",
    "Kannada (India)": "kn-IN",
    "Korean (South Korea)": "ko-KR",
    "Malayalam (India)": "ml-IN",
    "Mandarin Chinese (China)": "cmn-CN",
    "Marathi (India)": "mr-IN",
    "Norwegian Bokmål (Norway)": "nb-NO",
    "Polish (Poland)": "pl-PL",
    "Portuguese (Brazil)": "pt-BR",
    "Russian (Russia)": "ru-RU",
    "Spanish (Spain)": "es-ES",
    "Spanish (United States)": "es-US",
    "Swahili (Kenya)": "sw-KE",
    "Swedish (Sweden)": "sv-SE",
    "Tamil (India)": "ta-IN",
    "Telugu (India)": "te-IN",
    "Thai (Thailand)": "th-TH",
    "Turkish (Turkey)": "tr-TR",
    "Ukrainian (Ukraine)": "uk-UA",
    "Urdu (India)": "ur-IN",
    "Vietnamese (Vietnam)": "vi-VN",
}

GEMINI_TTS_LANGUAGES = {
    "Arabic (Egypt)": "ar-EG",
    "Dutch (Netherlands)": "nl-NL",
    "English (India)": "en-IN",
    "English (United States)": "en-US",
    "French (France)": "fr-FR",
    "German (Germany)": "de-DE",
    "Hindi (India)": "hi-IN",
    "Indonesian (Indonesia)": "id-ID",
    "Italian (Italy)": "it-IT",
    "Japanese (Japan)": "ja-JP",
    "Korean (South Korea)": "ko-KR",
    "Marathi (India)": "mr-IN",
    "Polish (Poland)": "pl-PL",
    "Portuguese (Brazil)": "pt-BR",
    "Romanian (Romania)": "ro-RO",
    "Russian (Russia)": "ru-RU",
    "Spanish (Spain)": "es-ES",
    "Tamil (India)": "ta-IN",
    "Telugu (India)": "te-IN",
    "Thai (Thailand)": "th-TH",
    "Turkish (Turkey)": "tr-TR",
    "Ukrainian (Ukraine)": "uk-UA",
    "Vietnamese (Vietnam)": "vi-VN",
    "Afrikaans (South Africa)": "af-ZA",
    "Albanian (Albania)": "sq-AL",
    "Amharic (Ethiopia)": "am-ET",
    "Arabic (World)": "ar-001",
    "Armenian (Armenia)": "hy-AM",
    "Azerbaijani (Azerbaijan)": "az-AZ",
    "Bangla (Bangladesh)": "bn-bd",
    "Basque (Spain)": "eu-ES",
    "Belarusian (Belarus)": "be-BY",
    "Bulgarian (Bulgaria)": "bg-BG",
    "Burmese (Myanmar)": "my-MM",
    "Catalan (Spain)": "ca-ES",
    "Cebuano (Philippines)": "ceb-PH",
    "Chinese, Mandarin (China)": "cmn-cn",
    "Chinese, Mandarin (Taiwan)": "cmn-tw",
    "Croatian (Croatia)": "hr-HR",
    "Czech (Czech Republic)": "cs-CZ",
    "Danish (Denmark)": "da-DK",
    "English (Australia)": "en-AU",
    "English (United Kingdom)": "en-GB",
    "Estonian (Estonia)": "et-EE",
    "Filipino (Philippines)": "fil-PH",
    "Finnish (Finland)": "fi-FI",
    "French (Canada)": "fr-CA",
    "Galician (Spain)": "gl-ES",
    "Georgian (Georgia)": "ka-GE",
    "Greek (Greece)": "el-GR",
    "Gujarati (India)": "gu-IN",
    "Haitian Creole (Haiti)": "ht-HT",
    "Hebrew (Israel)": "he-IL",
    "Hungarian (Hungary)": "hu-HU",
    "Icelandic (Iceland)": "is-IS",
    "Javanese (Java)": "jv-JV",
    "Kannada (India)": "kn-IN",
    "Konkani (India)": "kok-in",
    "Lao (Laos)": "lo-LA",
    "Latin (Vatican City)": "la-VA",
    "Latvian (Latvia)": "lv-LV",
    "Lithuanian (Lithuania)": "lt-IT",
    "Luxembourgish (Luxembourg)": "lb-LU",
    "Macedonian (North Macedonia)": "mk-MK",
    "Maithili (India)": "mai-IN",
    "Malagasy (Madagascar)": "mg-MG",
    "Malay (Malaysia)": "ms-MY",
    "Malayalam (India)": "ml-IN",
    "Mongolian (Mongolia)": "mn-MN",
    "Nepali (Nepal)": "ne-NP",
    "Norwegian, Bokmål (Norway)": "nb-NO",
    "Norwegian, Nynorsk (Norway)": "nn-NO",
    "Odia (India)": "or-IN",
    "Pashto (Afghanistan)": "ps-AF",
    "Persian (Iran)": "fa-IR",
    "Portuguese (Portugal)": "pt-PT",
    "Punjabi (India)": "pa-IN",
    "Serbian (Serbia)": "sr-RS",
    "Sindhi (India)": "sd-IN",
    "Sinhala (Sri Lanka)": "si-LK",
    "Slovak (Slovakia)": "sk-SK",
    "Slovenian (Slovenia)": "sl-SI",
    "Spanish (Latin America)": "es-419",
    "Spanish (Mexico)": "es-MX",
    "Swahili (Kenya)": "sw-KE",
    "Swedish (Sweden)": "sv-SE",
    "Urdu (Pakistan)": "ur-PK",
}
